/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baeldung_virtualthread_nativemethod_NativeDemo */

#ifndef _Included_com_baeldung_virtualthread_nativemethod_NativeDemo
#define _Included_com_baeldung_virtualthread_nativemethod_NativeDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baeldung_virtualthread_nativemethod_NativeDemo
 * Method:    nativeCall
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_baeldung_virtualthread_nativemethod_NativeDemo_nativeCall
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
